name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Files
      run: ls -la

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Files
      run: ls -la

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Install Serverless
      run: npm install -g serverless

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      run: npx serverless deploy --config /root/reactjs/my-lambda-project/serverless.yaml --stage production
